// Generated by https://quicktype.io

export interface CharacterResponsio {
    quote:              string;
    character:          string;
    image:              string;
    characterDirection: string;
}

